[[plugins]]
repo = "Shougo/ddc.vim"
depends = ['denops.vim', 'pum.vim']
on_event = ['InsertEnter', 'CursorHold']
hook_add = """
nnoremap : <cmd>call CmdlinePre(':')<CR>:
nnoremap ? <cmd>call CmdlinePre('/')<CR>?

function! CmdlinePre(mode) abort
  " NOTE: It disables default command line completion.
  cnoremap <expr> <TAB> pum#visible() ? '<cmd>call pum#map#insert_relative(+1)<CR>' : ddc#manual_complete()
  cnoremap <S-TAB> <cmd>call pum#map#insert_relative(-1)<CR>

  " Overwrite sources.
  let b:prev_buffer_config = ddc#custom#get_buffer()
  if a:mode ==# ':'
    call ddc#custom#patch_buffer('sources', ['cmdline', 'cmdline-history', 'around'])
    call ddc#custom#patch_buffer('keywordPattern', '[0-9a-zA-Z_:#]*')
  else
    call ddc#custom#patch_buffer('sources', ['around'])
  endif

  autocmd MyAutoCmd User DDCCmdlineLeave call CmdlinePost()

  " Enable command line completion.
  call ddc#enable_cmdline_completion()
  call ddc#enable()
endfunction

function! CmdlinePost() abort
  " Restore sources
  if exists('b:prev_buffer_config')
    call ddc#custom#set_buffer(b:prev_buffer_config)
    unlet b:prev_buffer_config
  endif

  silent! cunmap <TAB>
endfunction
"""
hook_source = """
call ddc#custom#patch_global('sourceOptions', {
      \ '_': {
      \   'matchers': ['matcher_head'],
      \   'sorters': ['sorter_rank'],
      \ },
      \ 'around': {
      \   'mark': 'A',
      \   'matchers': ['matcher_head'],
      \ },
      \ 'cmdline': {
      \   'mark': 'cmdline',
      \   'forceCompletionPattern': '\S/\S*',
      \ },
      \ 'cmdline-history': {
      \   'mark': 'history',
      \   'sorters': [],
      \ },
      \ })

" Use pum.vim
call ddc#custom#patch_global('autoCompleteEvents', [
      \ 'CmdlineEnter',
      \ 'CmdlineChanged',
      \ ])
call ddc#custom#patch_global('completionMenu', 'pum.vim')
"""

[[plugins]]
repo = "Shougo/pum.vim"

[[plugins]]
repo = "Shougo/ddc-around"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-cmdline"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-cmdline-history"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-matcher_head"
on_source = "ddc.vim"

[[plugins]]
repo = "Shougo/ddc-sorter_rank"
on_source = "ddc.vim"
