[[plugins]]
repo = "Shougo/ddu.vim"
depends = "denops.vim"
on_source = 'denops.vim'
hook_add = """
nnoremap <silent> ss
      \ <cmd>Ddu -name=files `finddir('.git', ';') != '' ? 'file_external' : 'file_rec'` -ui-param-startFilter<CR>
nnoremap <silent> /
      \ <cmd>Ddu -name=search line -ui-param-startFilter<CR>
nnoremap <silent> *
      \ <cmd>Ddu -name=search line -input=`expand('<cword>')`<CR>
nnoremap <silent> ;g
      \ <cmd>Ddu -name=search rg -ui-param-ignoreEmpty -source-param-input=`input('Pattern: ')`<CR>
nnoremap <silent> ;r
      \ <cmd>Ddu -buffer-name=register register -ui-param-autoResize<CR>
nnoremap <silent> sg
      \ <cmd>Ddu dein<CR>
"""
hook_source = """
call ddu#custom#patch_global({
      \ 'ui': 'ff',
      \ 'filterParams': {
      \   'matcher_substring': {
      \     'highlightMatched': 'Search',
      \   },
      \ },
      \ 'kindOptions': {
      \   'file': {
      \     'defaultAction': 'open',
      \   },
      \   'action': {
      \     'defaultAction': 'do',
      \   },
      \ },
      \ 'sourceOptions': {
      \   '_': {
      \     'matchers': ['matcher_substring'],
      \   },
      \   'file_external': {
      \     'matchers': ['matcher_fzf'],
      \   },
      \   'file_rec': {
      \     'matchers': ['matcher_substring', 'matcher_hidden'],
      \   },
      \   'rg': {
      \     'cmd': ['rg', '--files', '--glob', '!.git', '--color', 'never', '--no-messages'],
      \     'updateItems': 50000,
      \   },
      \ },
      \ 'sourceParams': {
      \   'file_external': {
      \     'cmd': ['git', 'ls-files', '-co', '--exclude-standard'],
      \   },
      \ },
      \ 'uiParams': {
      \   'ff': {
      \     'filterSplitDirection': has('nvim') ? 'floating' : 'botright',
      \     'prompt': '> ',
      \     'split': has('nvim') ? 'floating' : 'botright'
      \   },
      \ },
      \ })

call ddu#custom#patch_local('files', {
      \ 'uiParams': {
      \   'ff': {
      \     'previewFloating': v:true,
      \     'previewWidth': &columns / 2,
      \   },
      \ },
      \ })
"""
[plugins.ftplugin]
ddu-ff = """
nnoremap <buffer><silent> <CR>
      \ <cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> <SPACE>
      \ <cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> i
      \ <cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
nnoremap <buffer><silent> <C-l>
      \ <cmd>call ddu#ui#ff#do_action('refreshItems')<CR>
nnoremap <buffer><silent> p
      \ <cmd>call ddu#ui#ff#do_action('preview')<CR>
nnoremap <buffer><silent> q
      \ <cmd>call ddu#ui#ff#do_action('quit')<CR>
nnoremap <buffer><silent> a
      \ <cmd>call ddu#ui#ff#do_action('chooseAction')<CR>
nnoremap <buffer><silent> c
      \ <cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'cd'})<CR>
nnoremap <buffer><silent> v
      \ <cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'open', 'params': {'command': 'vsplit'}})<CR>
nnoremap <buffer><silent> r
      \ <cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'quickfix'})<CR>
nnoremap <buffer><silent> u
      \ <cmd>call ddu#ui#ff#do_action('updateOptions', {'sourceOptions': {'_': {'matchers': []}}})<CR>
"""
ddu-ff-filter = """
inoremap <buffer><silent> <CR>
      \ <ESC><cmd>close<CR>
nnoremap <buffer><silent> <CR>
      \ <cmd>close<CR>
"""

[[plugins]]
repo = "Shougo/ddu-commands.vim"
depends = "ddu.vim"
on_cmd = "Ddu"

[[plugins]]
repo = "Shougo/ddu-ui-ff"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-source-action"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-source-file_external"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-source-file_rec"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-source-line"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-source-register"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-source-rg"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-filter-matcher_substring"
on_source = "ddu.vim"

[[plugins]]
repo = "yuki-yano/ddu-filter-fzf"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-kind-file"
on_source = "ddu.vim"
